/***********************************
 * Copyright (c) 2024 Roger Brown.
 * Licensed under the MIT License.
 ****/

import "oaidl.idl"; 

[
	object,
	uuid(58fb54de-ae65-4676-8171-4ec1eceb1d9d),
	oleautomation,
	dual,
	helpstring("interface IHelloWorld")
]
interface IHelloWorld : IDispatch
{
	HRESULT GetMessage(int Hint,[retval,out] BSTR *lpMessage);
}

[
	uuid(40d40249-e837-40ef-afd2-e73564dec352),
	helpstring("OLESelfRegister Hello World Component 1.0 Type Library"), 
	version(1.0)
]
library RhubarbGeekNzDispLib
{
	importlib("stdole32.tlb");
	[uuid(74067a54-5baf-4cd0-bf21-db6a9efa6ca7),helpstring("CHelloWorld class")]
	coclass CHelloWorld
	{
		[default] interface IHelloWorld;
	};
}
